/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ModeloDao.DaoAgenda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;

/**
 *
 * @author USUARIO
 */
public class formConfirmacao extends javax.swing.JFrame {
ConexaoBD conex= new ConexaoBD();
DaoAgenda daoAgenda= new DaoAgenda();
String cod_ag;
String dtHoje;
String status;
    /**
     * Creates new form formConfirmacao
     */
    public formConfirmacao() {
        initComponents();
        preencherPet();
        Calendar data = Calendar.getInstance();
        Date d =data.getTime();
        SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
        
        
        dtHoje=dateFormat.format(d);
        status="atendimento";
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPet = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgenda = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAdotar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Adoção");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Pet");

        jComboBoxPet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPetActionPerformed(evt);
            }
        });

        tabelaAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAgenda);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adopt_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(jComboBoxPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAdotar.setText("Iniciar Adocao");
        btnAdotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btnAdotar)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdotar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(764, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPetActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int cod=daoAgenda.BuscaCodPet((String)jComboBoxPet.getSelectedItem());
        String codigo = String.valueOf(cod);
        
               preencherTabela("select * from agendamento inner join clientes on agenda_cliente_id=cliente_id inner join pets on agenda_pet_id=id_pet where agenda_pet_id='"+codigo+"'and agenda_data='"+dtHoje+"' and agenda_status='"+status+"'");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdotarActionPerformed
formConclusao tela = new formConclusao(cod_ag);
tela.setVisible(true);
dispose();
        
        
    }//GEN-LAST:event_btnAdotarActionPerformed

    private void tabelaAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendaMouseClicked
        cod_ag=""+tabelaAgenda.getValueAt(tabelaAgenda.getSelectedRow(),0);



        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAgendaMouseClicked
    public void preencherPet(){
        conex.conexao();
        conex.executaSql("select * from pets order by nome_pet");
    try {
        conex.rs.first();
        jComboBoxPet.removeAllItems();
        do{
            jComboBoxPet.addItem(conex.rs.getString("nome_pet"));
        }while(conex.rs.next());
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"erro"+ex);
    }}   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formConfirmacao().setVisible(true);
            }
        });
    }
    public void preencherTabela(String Sql){ //METODO PRENCHER TABELAS
    ArrayList dados=new ArrayList();
    String[]colunas=new String[]{"ID","Nome","Turno","Data","Pet","Status"};
    conex.conexao();
    conex.executaSql(Sql);
    try{
        conex.rs.first();
        do{
            dados.add(new Object[]{conex.rs.getInt("agenda_codigo"),conex.rs.getString("cliente_nome"),conex.rs.getString("agenda_turno"),conex.rs.getString("agenda_data"),conex.rs.getString("nome_pet"), conex.rs.getString("agenda_status")}); //inserindo array nas tabelas
        }while(conex.rs.next());
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Não há atendimento hoje");
        
    }
    ModeloTabela modelo= new ModeloTabela(dados, colunas);
    tabelaAgenda.setModel(modelo);
   tabelaAgenda.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabelaAgenda.getColumnModel().getColumn(0).setResizable(false);
    tabelaAgenda.getColumnModel().getColumn(1).setPreferredWidth(180);
    tabelaAgenda.getColumnModel().getColumn(1).setResizable(false);
    tabelaAgenda.getColumnModel().getColumn(2).setPreferredWidth(180);
    tabelaAgenda.getColumnModel().getColumn(2).setResizable(false);
    tabelaAgenda.getColumnModel().getColumn(3).setPreferredWidth(80);
   tabelaAgenda.getColumnModel().getColumn(3).setResizable(false);
    tabelaAgenda.getColumnModel().getColumn(4).setPreferredWidth(80);
   tabelaAgenda.getColumnModel().getColumn(4).setResizable(false);
    tabelaAgenda.getColumnModel().getColumn(5).setPreferredWidth(80);
   tabelaAgenda.getColumnModel().getColumn(5).setResizable(false);
    
    tabelaAgenda.getTableHeader().setReorderingAllowed(false);
    tabelaAgenda.setAutoResizeMode(tabelaAgenda.AUTO_RESIZE_OFF);//impede o usurio de alterar tamanho da tabela
    tabelaAgenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    conex.desconecta();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdotar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> jComboBoxPet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAgenda;
    // End of variables declaration//GEN-END:variables
}
