/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeloConection.ConexaoBD;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta=new ConexaoBD();
    formUsuario tela=new formUsuario();
    formPets telaPets=new formPets();
    formCliente telaCliente=new formCliente();
    formAgenda telaAgenda=new formAgenda();
    public TelaPrincipal(String Usuario) {
        initComponents();
        lblUsu.setText(Usuario);
        conecta.conexao();
       
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        btnAdocao = new javax.swing.JButton();
        lblAdocao = new javax.swing.JLabel();
        btnPets = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        lblCadastroJpainel = new javax.swing.JLabel();
        lblFundoJpainel = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblUsu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemPets = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuAdocao = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuPets = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        menuTeste = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBackground(new java.awt.Color(212, 220, 228));
        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        btnAdocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_adopt.png"))); // NOI18N
        btnAdocao.setText("fotoAdoção");
        btnAdocao.setToolTipText("Registrar Adoção");
        btnAdocao.setBorder(null);
        btnAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdocaoActionPerformed(evt);
            }
        });
        jPanelInternal.add(btnAdocao);
        btnAdocao.setBounds(10, 210, 90, 90);

        lblAdocao.setText("Adoção");
        jPanelInternal.add(lblAdocao);
        lblAdocao.setBounds(10, 180, 90, 20);

        btnPets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_cad_pet.png"))); // NOI18N
        btnPets.setText("fotoPets");
        btnPets.setToolTipText("Cadastrar Pets");
        btnPets.setBorder(null);
        btnPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetsActionPerformed(evt);
            }
        });
        jPanelInternal.add(btnPets);
        btnPets.setBounds(230, 60, 90, 90);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_cad_cli.png"))); // NOI18N
        btnCliente.setText("fotoClient");
        btnCliente.setToolTipText("Cadastrar Clientes");
        btnCliente.setBorder(null);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(btnCliente);
        btnCliente.setBounds(120, 60, 90, 90);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_cad_usu.png"))); // NOI18N
        btnUsuario.setText("foto Usuario");
        btnUsuario.setToolTipText("Cadastrar Usuários");
        btnUsuario.setBorder(null);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(btnUsuario);
        btnUsuario.setBounds(10, 60, 90, 90);

        lblCadastroJpainel.setText("Cadastros");
        jPanelInternal.add(lblCadastroJpainel);
        lblCadastroJpainel.setBounds(10, 20, 100, 20);

        lblFundoJpainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_cadastro.png"))); // NOI18N
        jPanelInternal.add(lblFundoJpainel);
        lblFundoJpainel.setBounds(80, 7, 970, 310);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 80, 1050, 320);

        lblTitulo.setBackground(new java.awt.Color(255, 204, 102));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Sistema de Gerenciamento de: ");
        jInternalFrameBemVindo.getContentPane().add(lblTitulo);
        lblTitulo.setBounds(10, 10, 260, 22);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        btnSair.setToolTipText("Fechar Tela Bem-Vindo");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(btnSair);
        btnSair.setBounds(990, 0, 40, 40);

        lblUsu.setText("jLabel1");
        jInternalFrameBemVindo.getContentPane().add(lblUsu);
        lblUsu.setBounds(120, 480, 120, 16);

        jLabel2.setText("Usuário");
        jInternalFrameBemVindo.getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 480, 70, 16);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 160, 1050, 560);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_principal_novo.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(-70, -50, 1930, 890);

        jMenuCadastro.setText("Cadastro");

        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuItemPets.setText("Pets");
        jMenuItemPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPetsActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPets);

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuBar1.add(jMenuCadastro);

        jMenuAdocao.setText("Adoção");

        jMenuItem1.setText("Agendamento de Adoção");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAdocao.add(jMenuItem1);

        jMenuItem2.setText("Agenda do dia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAdocao.add(jMenuItem2);

        jMenuBar1.add(jMenuAdocao);

        jMenuPets.setText("Pets");
        jMenuBar1.add(jMenuPets);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        menuTeste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuTeste.setText("Teste");
        menuTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTesteActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(menuTeste);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenuSair.add(Sair);

        jMenuBar1.add(jMenuSair);

        jMenu1.setText("Canil");

        jMenuItem3.setText("Confirmação da Adoção");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1870, 894));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPetsActionPerformed
try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaPets==null){
                    telaPets=new formPets();
                    telaPets.setVisible(true);
                    telaPets.setResizable(false);
                }else{
                telaPets.setVisible(true);
                telaPets.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
      
    }//GEN-LAST:event_jMenuItemPetsActionPerformed

    private void btnAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdocaoActionPerformed

        try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaAgenda==null){
                   telaAgenda=new formAgenda();
                    telaAgenda.setVisible(true);
                    telaAgenda.setResizable(false);
                }else{
               telaAgenda.setVisible(true);
              telaAgenda.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdocaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
      conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameBemVindo.setVisible(true);
        //kmkmm
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
        try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaPets==null){
                    telaPets=new formPets();
                    telaPets.setVisible(true);
                    telaPets.setResizable(false);
                }else{
                telaPets.setVisible(true);
                telaPets.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
      
        
        
        
        
        
    }//GEN-LAST:event_btnPetsActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
         try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(tela==null){
                    tela=new formUsuario();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                tela.setVisible(true);
                tela.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
      
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void menuTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTesteActionPerformed
       // int confirma=JOptionPane.showConfirmDialog(null, "Confirma a impressão do Relatório", "Atenção",JOptionPane.YES_NO_OPTION);
        //if(confirma==JOptionPane.YES_OPTION){
          //  String src="C:/Users/USUÁRIO/JaspersoftWorkspace/MyReports\bin/teste.jasper";
            //JasperPrint jasperPrint=null;
            
         //try{
           //  jasperPrint=JasperFillManager.fillReport(src,null, con);
         //}catch(EXception e){
         //    JOptionPane.showMessageDialog(rootPane,"Erro ao gerar Relatório +ex");
        //}
         //JasperViewer view =JasperViewer(jasperPrint, false);
        //}


        // TODO add your handling code here:
    }//GEN-LAST:event_menuTesteActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed

try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(tela==null){
                    tela=new formUsuario();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                tela.setVisible(true);
                tela.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaCliente==null){
                   telaCliente=new formCliente();
                    telaCliente.setVisible(true);
                    telaCliente.setResizable(false);
                }else{
                telaCliente.setVisible(true);
                telaCliente.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaCliente==null){
                   telaCliente=new formCliente();
                    telaCliente.setVisible(true);
                    telaCliente.setResizable(false);
                }else{
                telaCliente.setVisible(true);
                telaCliente.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }   
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

 try {
             conecta.executaSql("select * from usuarios where usu_nome='"+ lblUsu.getText()+"'"); 
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                if(telaAgenda==null){
                   telaAgenda=new formAgenda();
                    telaAgenda.setVisible(true);
                    telaAgenda.setResizable(false);
                }else{
               telaAgenda.setVisible(true);
              telaAgenda.setResizable(false);
                }
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Voce não tem permissão para essa funcionalidade\n contate o administrador do sistema"+ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
formAgendaDia tela = new formAgendaDia();
tela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
formConfirmacao tela=new formConfirmacao();
tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sair;
    private javax.swing.JButton btnAdocao;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnPets;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAdocao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemPets;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuPets;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    private javax.swing.JLabel lblAdocao;
    private javax.swing.JLabel lblCadastroJpainel;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblFundoJpainel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JMenuItem menuTeste;
    // End of variables declaration//GEN-END:variables
}
